//
// Copyright 2009 Bill Casarin <billcasarin@gmail.com>
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
package twitter

import "testing"
import "os"

const kId = 5641609144;


func TestStatusWellFormed(t *testing.T) {
  api := NewApi();
  errors := api.GetErrorChannel();
  status := make([]Status, 2);
  var id int64 = kId;

  statusChan := api.GetStatusAsync(kId);
  status[1] = api.GetStatus(kId);
  status[0] = <-statusChan;

  if !StatusEqual(status[0], status[1]) {
    t.Errorf("GetStatusAsync(%d) != GetStatus(%d), expected ==", id, id);
  }

  s := status[0];
  t.Logf("Status Struct: %v", s);
  verifyValidStatus(s, t, 0);

  getAllApiErrors(errors, t);
}

func TestPublicTimeLineWellFormed(t *testing.T) {
  api := NewApi();
  errors := api.GetErrorChannel();
  statuses := api.GetPublicTimeline();
  length := len(statuses);

  if length <= 1 {
    t.Errorf("len(GetPublicTimeline()) <= 1, got %d expected > 1", length);
  }

  if StatusEqual(statuses[0], statuses[1]) {
    t.Errorf("GetPublicTimeline()[0] == GetPublicTimeline()[1], expected different");
  }

  t.Logf("Number of Statuses retrieved: %d", length);
  for i, status := range statuses {
    verifyValidStatus(status, t, i);
  }

  getAllApiErrors(errors, t);
}

// Authfile: .twitterauth
// Format: single line, two words
//    username password
func authFromFile() {
  return;
}

func verifyValidStatus(s Status, t *testing.T, i int) {
  const kFormat = "Status Struct #%d: %v";
  var numErrors int = 0;

  if val := s.GetId(); val <= 0 {
    t.Errorf("Status.GetId() is <= 0, got %d expected > 0", val);
    numErrors++;
  }

  if IsEmpty(s.GetCreatedAt()) {
    t.Error("Status.GetCreatedAt() is empty, expected not empty");
    numErrors++;
  }

  if IsEmpty(s.GetText()) {
    t.Error("Status.GetText() is empty, expected not empty");
    numErrors++;
  }

  if numErrors > 0 {
    t.Logf(kFormat, i, s);
  }

}

func getAllApiErrors(errors chan os.Error, t *testing.T) {
  if len(errors) == 0 {
    return;
  }
  t.Log("--- Errors generated by GoTwitter START ----");
  for ;; {
    err, hasErrors := <-errors;
    if hasErrors {
      t.Log(err.String());
    } else {
      break;
    }
  }
  t.Error("--- Errors generated by GoTwitter END ----");
}

func IsEmpty(s string) bool {
  return len(s) == 0;
}

func StatusEqual(a, b Status) bool {
  return a.GetCreatedAt() == b.GetCreatedAt() &&
         a.GetCreatedAtInSeconds() == b.GetCreatedAtInSeconds() &&
         a.GetFavorited() == b.GetFavorited() &&
         a.GetId() == b.GetId() &&
         a.GetInReplyToScreenName() == b.GetInReplyToScreenName() &&
         a.GetInReplyToStatusId() == b.GetInReplyToStatusId() &&
         a.GetInReplyToUserId() == b.GetInReplyToUserId() &&
         a.GetNow() == b.GetNow();
}
